apiVersion: alpha
kind: checker
metadata:
  name: "http-dive"
  labels:
    a: b
    c: d
spec:
  kind: http
  spec:
    notifier: dingtalk-basic
    # true: 此配置不生效, false 此配置生效
    disable: true
    reportTimes: 3
    url: "http://dive.cloud.51.net"
    cron: "0/5 * * * * ?"
    mustContain:
      - "o"
      - "k"
    mustNotContain:
      - "red"
