apiVersion: alpha
kind: checker
metadata:
  name: "tcp-dev-im"
  labels:
    a: b
    c: d
spec:
  kind: tcp
  spec:
    notifier: dingtalk-basic
    disable: false
    reportTimes: 3
    address: "im.tcp.net:8087"
    cron: "0/5 * * * * ?"
    mustContain:
      - "o"
      - "k"
    mustNotContain:
      - "red"
